server:
  port: 8081
  servlet:
    context-path: /api/v1/examTicket-service

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      group:
        db:
          include:
            - db
          show-components: always
          show-details: always

spring:
  datasource:
    hikari: # пулом соединений HikariCP, который проверяет соединение с базой данных
      max-lifetime: 20000 # максимального времени жизни соединения 20 секунд
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      naming:
        # стратегию именования, которая задает метод генерации физических имен таблиц и столбцов в базе данных
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      # означает что будет автоматически обновлять схему базы данных, если она не соответствует текущей модели данных
      ddl-auto: update
  cache:
    type: simple
    cache-names: rowCountCache
    caffeine:
      spec: expireAfterWrite=60m

scheduling:
  initialDelay: PT5M
  fixedDelay: PT1H

bot:
  userName: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}
  parseMode: HTML

logging:
  level:
    root: info